sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cjUInstaxsSUtYTuFBNIXtbfCHdVHji068kTaE8FbYf5L81SK8oD/MlHqTPsjoFIEjpgIluvem+Be/QXwIKJlKsd/MyoIuvtjKAviyHnea38DemDgnbsrt3a6Rbw8mmtBTsH5FyvcCcbbRgXtd5JkjOIBuGgZiCT3mOqHNbXfYFnYkLoq3tt/IjAOwwzQkMluGRx+vcS5z/VLA/UGuDM4pxJ1aDQz5rZRj5k3lBoRX7b7FXgTUK4otupp63ZaTnkLRk+KGKMVeED/OT9JrBZA2Qs31C++TTMceAZnYV1FQKHaxoVZ3GMVdDuEKBzQHQ9jATEZqr0Y9GRzf00bqbhOriDxDOktOa3vf8Vk1wzmVg0PYLCAZSNN0yaSG//9E6LmN35Wlw8HplvWLw1xdJ6w1RfGnYmB40pMOjc/xpTEHnst7PZ471XueKD+XQRyG2r3IXnXzWmHAJ1mWBLG2oVUaViLUHz8kv3gNkRRDJbWnCwwLeQUDK1sypsY9KiH+y8CVr4lac4AFc8MT4p3dsJQRWx7VbTfR4EGzZZBJROVpxX+sb+cxBn8+EQP9XXmdrHSsNpCbtSF92AmeBESFHtWFnuPwsXn2zgVDvHyuhln1rvn567lYSJY/ocwyVk/UZLRnzgBJe+17SbZEDXeaz//XjMz8LcFb2KB9+qxIZjdUs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/From-the-Earth-to-the-Moon--and-Round-the-Moon_83
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy